version: '3.3'

services:
    db:
        build:
            context: database
            dockerfile: Dockerfile
        hostname: db
        container_name: db
        networks:
            - hotel_reservation

    db-seed:
        build:
            context: ./database/database_seed
            dockerfile: Dockerfile
        hostname: db-seed
        container_name: db-seed
        networks:
            - hotel_reservation

    backend:
        build:
            context: backend
            target: production
            dockerfile: Dockerfile
        hostname: backend
        container_name: backend
        depends_on:
            - db
        networks:
            - hotel_reservation
        environment:
            PORT: 5000
            NODE_ENV: production
            MONGO_URI: mongodb://db/HotelReservation?directConnection=true&retryWrites=true&w=majority
            JWT_SECRET: asdfghjkl;;lkjhgfdsa
            JWT_EXPIRE: 30d
            JWT_COOKIE_EXPIRE: 30

    frontend:
        build:
            context: frontend
            target: production
            dockerfile: Dockerfile
        hostname: frontend
        container_name: frontend
        depends_on:
            - backend
        networks:
            - hotel_reservation
        ports:
            - '3000:3000'
        environment:
            NEXTAUTH_URL: http://localhost:3000/
            NEXTAUTH_SECRET: 'Ey7nTKnggBc0bRN8WUjyShw2qzOZ6KW4fUyqcKBePxY='
            MONGO_URI: mongodb://db/HotelReservation?directConnection=true&retryWrites=true&w=majority
            FRONTEND_URL: http://localhost:3000
            BACKEND_URL: http://localhost:5000

networks:
    hotel_reservation:
        name: hotel_reservation
